spring:
  application:
    name: omo-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: 你的api-key
      chat:
        options:
          model: qwen-plus
    vectorstore:
      pgvector:
              index-type: HNSW
              distance-type: cosine_distance
              dimensions: 1536
              max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
#    mcp:
#      client:
#              timeout: 60000
#              stdio:
#                servers-configuration: classpath:mcp-servers.json

# 数据库配置
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres



# 服务器启动配置
server:
    port: 8123
    servlet:
      context-path: /api

# springdoc-openapi项目配置（knife4j）:
# http://localhost:8123/api/doc.html#/home
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.erokin.omoaiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchApi
search-api:
  api-key: 你的api-key